name: Publish to PyPI

on:
  push:
    tags:
      - 'v*'
  workflow_dispatch:

permissions:
  contents: write
  packages: write

jobs:
  build-and-publish:
    runs-on: ubuntu-latest
    
    steps:
    - name: Checkout code
      uses: actions/checkout@v4
      with:
        fetch-depth: 0
      
    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.11'
        
    - name: Install build dependencies
      run: |
        python -m pip install --upgrade pip
        pip install build twine wheel
        
    - name: Build package
      run: |
        python -m build
        
    - name: Check package
      run: |
        twine check dist/*
        
    - name: Publish to PyPI
      env:
        TWINE_USERNAME: __token__
        TWINE_PASSWORD: ${{ secrets.PYPI_API_TOKEN }}
      run: |
        twine upload dist/*

    - name: Create GitHub Release
      run: |
        # Create release notes
        cat > release_notes.md << 'EOF'
        ## Changes in ${{ github.ref_name }}
        
        This release includes:
        - PDF unlocking functionality using multiple methods
        - Password memory system for faster processing
        - Command-line interface with flexible options
        - Support for batch processing and custom directories
        
        ## Installation
        
        ```bash
        pip install upppdf
        ```
        
        ## Usage
        
        ```bash
        # Unlock all PDFs in current directory
        upppdf
        
        # Unlock specific file
        upppdf -f document.pdf
        
        # Show help
        upppdf --help
        ```
        EOF
        
        # Create the release
        gh release create ${{ github.ref_name }} \
          --title "Release ${{ github.ref_name }}" \
          --notes-file release_notes.md \
          dist/*.whl dist/*.tar.gz
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}