name: Update Homebrew Formula

on:
  release:
    types: [published]

jobs:
  update-homebrew:
    runs-on: ubuntu-latest
    
    steps:
    - name: Checkout homebrew-tap
      uses: actions/checkout@v4
      with:
        repository: abozaralizadeh/homebrew-brew
        token: ${{ secrets.GITHUB_TOKEN }}
        path: homebrew-tap
        
    - name: Get release info
      id: release
      run: |
        echo "version=${GITHUB_REF#refs/tags/v}" >> $GITHUB_OUTPUT
        echo "url=https://github.com/${{ github.repository }}/archive/refs/tags/${{ github.ref_name }}.tar.gz" >> $GITHUB_OUTPUT
        
    - name: Calculate SHA256
      id: sha256
      run: |
        SHA256=$(curl -sL ${{ steps.release.outputs.url }} | shasum -a 256 | cut -d' ' -f1)
        echo "sha256=$SHA256" >> $GITHUB_OUTPUT
        
    - name: Update Formula
      run: |
        cd homebrew-tap
        sed -i "s|url \".*\"|url \"${{ steps.release.outputs.url }}\"|" Formula/upppdf.rb
        sed -i "s|sha256 \".*\"|sha256 \"${{ steps.sha256.outputs.sha256 }}\"|" Formula/upppdf.rb
        
    - name: Commit and push
      run: |
        cd homebrew-tap
        git config --local user.email "action@github.com"
        git config --local user.name "GitHub Action"
        git add Formula/upppdf.rb
        git commit -m "Update upppdf to ${{ steps.release.outputs.version }}"
        git push
