name: Update Homebrew Formula

on:
  release:
    types: [published]

permissions:
  contents: write

jobs:
  update-homebrew:
    runs-on: ubuntu-latest
    
    steps:
    - name: Checkout main repository
      uses: actions/checkout@v4
      with:
        fetch-depth: 0
        
    - name: Get release info
      id: release
      run: |
        echo "version=${GITHUB_REF#refs/tags/v}" >> $GITHUB_OUTPUT
        echo "url=https://github.com/abozaralizadeh/UPPPDF/archive/refs/tags/${{ github.ref_name }}.tar.gz" >> $GITHUB_OUTPUT
        
    - name: Calculate SHA256
      id: sha256
      run: |
        SHA256=$(curl -sL ${{ steps.release.outputs.url }} | shasum -a 256 | cut -d' ' -f1)
        echo "sha256=$SHA256" >> $GITHUB_OUTPUT
        
    - name: Update Formula
      run: |
        # Update the formula file in the main repository
        sed -i "s|url \".*\"|url \"${{ steps.release.outputs.url }}\"|" homebrew-tap/Formula/upppdf.rb
        sed -i "s|sha256 \".*\"|sha256 \"${{ steps.sha256.outputs.sha256 }}\"|" homebrew-tap/Formula/upppdf.rb
        
    - name: Commit and push changes
      run: |
        git config --local user.email "action@github.com"
        git config --local user.name "GitHub Action"
        git add homebrew-tap/Formula/upppdf.rb
        git commit -m "Update upppdf formula to ${{ steps.release.outputs.version }}"
        git push